global:
  storageClass: longhorn
webapp:
  ingress:
    enabled: false
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: 'true'
      hajimari.io/group: Infrastructure
    hosts:
      - host: &host airbyte.quill.local
        paths:
          - /
    tls: 
      - secretName: airbyte-tls-certificate
        hosts:
          - *host