global:
  storageClass: longhorn
webapp:
  ingress:
    enabled: true
    className: traefik
    annotations:
      # kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      hajimari.io/enable: 'true'
      hajimari.io/group: Infrastructure
    hosts:
      - host: &host airbyte.quillte.ch
        paths:
          - /
    tls: 
      - secretName: airbyte-tls-certificate
        hosts:
          - *host