hajimari:
  image:  # TODO remove this https://github.com/toboshii/hajimari/blob/main/charts/hajimari/values.yaml
    tag: v0.2.0
  env:
    TZ: America/Los_Angeles
  ingress:
    main:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "false"
      hosts:
        - host: "home.quillte.ch"
          path: /
          pathType: Prefix
          service:
            name: hajimari
            port: 3000
      tls:
        - secretName: hajimari-tls-certificate
          hosts:
            - "home.quillte.ch"
  hajimari:
    defaultEnable: true
    namespaceSelector:
      any: true
    groups:
      - name: Homelab
        links:
          - name: Documentation
            url: https://homelab.khuedoan.com
          - name: Public GitHub repository
            url: https://github.com/cmcquillan/quillhome
      - name: Managed services
        links:
          - name: Terraform Cloud
            url: https://app.terraform.io
          - name: Cloudflare
            url: https://dash.cloudflare.com