apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-inside-lovequillprevail-com-tls
spec:
  secretName: wildcard-inside-lovequillprevail-com-tls
  dnsNames:
    - "*.inside.lovequillprevail.com"
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer