apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`traefik.quillte.ch`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      priority: 10
      services:
        - name: api@internal
          kind: TraefikService
  tls: {}