# issuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: casey.mcquillan@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cnameStrategy: Follow
          route53:
            region: us-east-1
            accessKeyID: <Access ID for less-privileged.example.org here>
            hostedZoneID: Z08851351A6ML6ZTSK0XN
            secretAccessKeySecretRef:
              name: aws-route53-key
              key: accessKey