apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
  - ingress.yaml

## changes to config maps
patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yaml

namespace: argocd