argo-cd:
  crds:
    install: true
  cm:
    create: true
  redis:
    dnsConfig: {}
  applicationSet:
    dnsConfig: {}
  notifications:
    dnsConfig: {}
  controller:
    dnsConfig: {}
  repoServer:
    dnsConfig:
      options:
        - name: ndots
          value: "6"
  server:
    dnsConfig: {}