longhorn:
  defaultSettings:
    nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  persistence:
    defaultClassReplicaCount: 1 
    defaultClass: false
  helmPreUpgradeCheckerJob:
    enabled: false
  enablePSP: false