{{- $secret := (lookup "v1" "Secret" .Release.Namespace "pgdata-auth") -}}
apiVersion: v1
kind: Secret
metadata:
  name: pgdata-auth
data:
  {{- if $secret }}
  postgres-password: {{ index $secret.data "postgres-password" }}
  password: {{ index $secret.data "password" }}
  replication-password: {{ index $secret.data "replication-password" }}
  {{ else }}
  postgres-password: {{ randAlphaNum 20 | b64enc }}
  password: {{ randAlphaNum 20 | b64enc }}
  replication-password: {{ randAlphaNum 20 | b64enc }}
  {{ end }}