{{- $secret := (lookup "v1" "Secret" .Release.Namespace "pgdata-auth") -}}
apiVersion: v1
kind: Secret
metadata:
  name: pgdata-auth
data:
  postgres-password: {{ index $secret.data "postgres-password" | default (randAlphaNum 20 | b64enc) }}
  password: {{ index $secret.data "password" | default (randAlphaNum 20 | b64enc) }}
  replication-password: {{ index $secret.data "replication-password" | default (randAlphaNum 20 | b64enc) }}