{{- $pgpass := (index (lookup "v1" "Secret" .Release.Namespace "pgdata-auth").data "postgres-password") -}}
{{- $quillpass := (index (lookup "v1" "Secret" .Release.Namespace "pgdata-auth").data "password") -}}
{{- $reppass := (index (lookup "v1" "Secret" .Release.Namespace "pgdata-auth").data "replication-password") -}}
apiVersion: v1
kind: Secret
metadata:
  name: pgdata-auth
data:
  postgres-password: {{ $pgpass | default (randAlphaNum 20 | b64enc) }}
  password: {{ $quillpass | default (randAlphaNum 20 | b64enc) }}
  replication-password: {{ $reppass | default (randAlphaNum 20 | b64enc) }}