apiVersion: v1
kind: Secret
metadata:
  name: pgdata-auth
data:
  {{- if .Release.IsInstall }}
  postgres-password: {{ randAlphaNum 20 | b64enc }}
  password: {{ randAlphaNum 20 | b64enc }}
  replication-password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  # `index` function is necessary because the property name contains a dash.
  # Otherwise (...).data.db_password would have worked too.
  postgres-password:  {{ index (lookup "v1" "Secret" .Release.Namespace "pgdata-auth").data "postgres-password" }}
  password:  {{ index (lookup "v1" "Secret" .Release.Namespace "pgdata-auth").data "password" }}
  replication-password:  {{ index (lookup "v1" "Secret" .Release.Namespace "pgdata-auth").data "replication-password" }}
  {{ end }}
  