trow:
  trow:
    domain: registry.quillte.ch
    validation:
      enabled: false
      allowDocker: false
      allowKubernetes: true
      allowPrefixes: []
      allowImages: []
      disallowLocalPrefixes: []
      disallowLocalImages: []
      proxyDockerHub: false

  ingress:
    enabled: true  # TODO https://github.com/ContainerSolutions/trow/issues/282
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
      hajimari.io/enable: 'true'
      hajimari.io/group: Infrastructure
    hosts:
      - host: &host registry.quillte.ch
        paths:
          - /
    tls:
      - secretName: trow-tls-certificate
        hosts:
          - *host
  volumeClaim:
    storageClassName: longhorn