trow:
  trow:
    domain: registry.inside.lovequillprevail.com
    validation:
      enabled: false
      allowDocker: false
      allowKubernetes: true
      allowPrefixes: []
      allowImages: []
      disallowLocalPrefixes: []
      disallowLocalImages: []
      proxyDockerHub: false
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/enable: 'true'
      hajimari.io/group: Infrastructure
    hosts:
      - host: &host registry.inside.lovequillprevail.com
        paths:
          - /
    tls:
      - secretName: trow-tls-certificate
        hosts:
          - *host
  volumeClaim:
    storageClassName: longhorn