ingressClass:
  enabled: true
  isDefaultClass: true
rbac:
  enabled: true
ports:
  websecure:
    http:
      tls:
        enabled: true
tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-inside-lovequillprevail-com-tls
logs:
  access:
    enabled: true
  general:
    level: DEBUG
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
globalArguments:
  - "--api.insecure=true"
    