ingressClass:
  enabled: true
  isDefaultClass: true
rbac:
  enabled: true
ports:
  websecure:
    http:
      tls:
        enabled: true
logs:
  access:
    enabled: true
  general:
    level: DEBUG
accessLog:
  filePath: "/var/traefik/access.log"
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
globalArguments:
  - "--api.insecure=true"
priorityClassName: "system-cluster-critical"
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
