rbac:
  enabled: true
ports:
  websecure:
    address: ':443'
    http:
      tls:
        enabled: true
logs:
  general:
    level: DEBUG
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
globalArguments:
  - "--api.insecure=true"
priorityClassName: "system-cluster-critical"
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
