apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hajimari
  namespace: hajimari
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`home.quillte.ch`)
      priority: 10
      services:
        - name: hajimari
          port: 80
  tls: {}
    